import { Inter } from 'next/font/google'
import '../styles/globals.css';
import Nav from '../components/Nav'
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Safe Transfer Crypto',
  description: 'Generated by Prince Rathi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        
      <main className="app">
        <Nav />
        
        <Providers>

        {children}
        </Providers>
        
      </main>
      </body>
      
    </html>
  )
}
